FROM nowk/ruby-base:2.2.3
MAINTAINER Yung Hwa Kwon <yung.kwon@damncarousel.com>

# install bundler and create the source dir
ONBUILD RUN gem install bundler \
	&& mkdir -p /src

# add user ruby, so we don't have to bundle under root
# USER must be explicitly called in your Dockerfile
ONBUILD RUN adduser --disabled-password --uid 1000 --gecos '' ruby \
	&& echo "ruby ALL=(ALL:ALL) ALL" >> /etc/sudoers \
	&& mkdir -p /src \
	&& chown -R ruby:ruby /src

# install the gems to mounted volume as .bundle
ONBUILD ENV GEM_HOME /src/.bundle
ONBUILD ENV BUNDLE_APP_CONFIG $GEM_HOME
ONBUILD ENV PATH $GEM_HOME/bin:$PATH
ONBUILD RUN bundle config --global path "$GEM_HOME" \
	&& bundle config --global bin "$GEM_HOME/bin"


# /src is the mounted source volume
ONBUILD VOLUME /src

# /src is the working dir
ONBUILD WORKDIR /src
